### ISSUE TITLE
Self Identified: BH Device utilization faliure || Repeated Devices

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#61]
Mentioned devices which are generating BH polling graph over W1, Still they are reflects in BH polling failure report.
10.175.21.37
172.21.61.202

**Comment by santoshkhairnar-tm** [comment]
This is reporting issue, This was solved by Rohit but this cases again reflects in BH polling failure report.

**Comment by rupalivaidya-tm** [comment]
Issue is still occurring with only this mentioned cases. Team is working on it.
10.175.21.37
172.21.61.202

**Comment by rupalivaidya-tm** [comment]
Issue is still occurring with only this mentioned cases. Team is working on it.
10.175.21.37
172.21.61.202

**Comment by rupalivaidya-tm** [comment]
Issue is still occurred in today's report for same IPs

**Comment by rupalivaidya-tm** [comment]
Multiple entries present for both IPs in Database. Team is working on it.

**Comment by rupalivaidya-tm** [comment]
Issue Resolved. Under Observation.

**RCA:**Multiple entries present for both IPs in Database. Team is working on it.

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.
@rohitgupta-tm - please close this issue.
